# Generated by Django 4.0.1 on 2022-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoLab', '0002_alter_client_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
